

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    REFRESH_REQUEST: 'REFRESH_REQUEST',
    REFRESH_FAILURE: 'REFRESH_FAILURE',
    REFRESH_SUCCESS: 'REFRESH_SUCCESS',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS'

}

export const courseConstants = {
    FETCH_COURSE_REQUEST: 'FETCH_COURSE_REUEST',
    FETCH_COURSE_FAILURE: 'FETCH_COURSE_FAILURE',
    FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
    FETCH_LECTURERS_REQUEST: 'FETCH_LECTURERS_REQUEST',
    FETCH_LECTURERS_FAILURE: 'FETCH_LECTURERS_FAILURE',
    FETCH_LECTURERS_SUCCESS: 'FETCH_LECTURERS_SUCCESS'
}