export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

  REFRESH_REQUEST: 'REFRESH_REQUEST',
  REFRESH_FAILURE: 'REFRESH_FAILURE',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
};

export const walletConstants = {
  FETCH_WALLET_REQUEST: 'FETCH_WALLET_REQUEST',
  FETCH_WALLET_FAILURE: 'FETCH_WALLET_FAILURE',
  FETCH_WALLET_SUCCESS: 'FETCH_WALLET_SUCCESS',

  FUND_WALLET_REQUEST: 'FUND_WALLET_REQUEST',
  FUND_WALLET_FAILURE: 'FUND_WALLET_FAILURE',
  FUND_WALLET_SUCCESS: 'FUND_WALLET_SUCCESS',

  CHECKOUT_WALLET_REQUEST: 'FUND_WALLET_REQUEST',
  CHECKOUT_WALLET_FAILURE: 'FUND_WALLET_FAILURE',
  CHECKOUT_WALLET_SUCCESS: 'FUND_WALLET_SUCCESS',

  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  SET_PIN_FAILURE: 'SET_PIN_FAILURE',
};

export const transactionConstants = {
  FETCH_TRANSACTIONS_REQUEST: 'FETCH_TRANSACTIONS_REQUEST',
  FETCH_TRANSACTIONS_FAILURE: 'FETCH_TRANSACTIONS_FAILURE',
  FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
};

export const uiConstants = {
  SWITCH_MODE_LIGHT: 'SWITCH_MODE_LIGHT',
  SWITCH_MODE_DARK: 'SWITCH_MODE_DARK',
};
